services:
    traefik:
        container_name: traefik
        image: traefik:latest
        restart: unless-stopped
        ports:
            - "127.0.0.1:80:80"
            - "127.0.0.1:443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.yml:/etc/traefik/traefik.yml:delegated
            - ./traefik_dynamic_conf.yml:/etc/traefik/traefik_dynamic_conf.yml:delegated
            - ./certs:/certs:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            - "traefik.http.routers.traefik.entrypoints=http"
            - "traefik.http.routers.traefik.rule=Host(`traefik.docker.local`)"

networks:
    default:
        name: traefik
        external: true
