http:
    middlewares:
        redirect-to-https:
            redirectScheme:
                scheme: "https"
                permanent: true

tls:
    options:
        default:
            minVersion: VersionTLS12
    certificates:
        - certFile: "/certs/hr-rail.local.crt"
          keyFile: "/certs/hr-rail.local.key"
