global:
    sendAnonymousUsage: false

log:
    level: WARNING

entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"

providers:
    file:
        filename: "/etc/traefik/traefik_dynamic_conf.yml"
        watch: true
    docker:
        exposedByDefault: false
        watch: true

api:
    dashboard: true
    debug: true
    insecure: true
